version: 2
references:
  pre_setup: &pre_setup
    run:
      name: Install System Packages
      command: |
        apt-get update
        apt-get full-upgrade -y
        apt-get -y install libsodium18 libsodium-dev pkg-config clang unzip cmake make binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev
        export ANDROID_NDK_HOME=/opt/android-ndk/android-ndk-r17c/
        mkdir -p /opt/android-ndk/
        apt-get install openjdk-8-jdk -y
        CWD=$(pwd)
        cd /opt/android-ndk/
        wget https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
        unzip android-ndk-r17c-linux-x86_64.zip
        cd $CWD
        ./create-ndk-standalone.sh

  setup_rust: &setup_rust
    run:
      name: Setup nightly
      command: |
        rustup default nightly
        rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios
        rustup target add aarch64-linux-android armv7-linux-androideabi
        rustup update
        rustup show

  build_dev: &build_dev
    run:
      name: Build project debug
      command: |
        export CC=clang
        export CXX=clang++
        cargo build -p dmbc -p dmbc-node -p dmbc-discovery -p dmbc-capi -vv

  build_dev_mobile: &build_dev_mobile
    run:
      name: Build CAPI project mobile debug
      command: |
        export CC=clang
        export CXX=clang++
        mkdir .cargo
        cat cargo-config.toml >> .cargo/config
        cargo build -p dmbc-capi --target aarch64-linux-android -vv
        cargo build -p dmbc-capi --target armv7-linux-androideabi -vv

        # cargo build -p dmbc-capi --target aarch64-apple-ios --lib -vv
        # cargo build -p dmbc-capi --target armv7-apple-ios --lib -vv
        # cargo build -p dmbc-capi --target armv7s-apple-ios --lib -vv

  build_prod: &build_prod
    run:
      name: Build project prod
      command: |
        export CC=clang
        export CXX=clang++
        cargo build -p dmbc -p dmbc-node -p dmbc-discovery -p dmbc-capi -vv --release

  build_prod_mobile: &build_prod_mobile
    run:
      name: Build CAPI project mobile debug
      command: |
        export CC=clang
        export CXX=clang++
        mkdir .cargo
        cat cargo-config.toml >> .cargo/config
        cargo build -p dmbc-capi --target aarch64-linux-android -vv --release
        cargo build -p dmbc-capi --target armv7-linux-androideabi -vv --release

        # cargo build -p dmbc-capi --target aarch64-apple-ios --lib -vv
        # cargo build -p dmbc-capi --target armv7-apple-ios --lib -vv
        # cargo build -p dmbc-capi --target armv7s-apple-ios --lib -vv

  run_tests: &run_tests
    run:
      name: Run Tests
      command: |
        export CC=clang
        export CXX=clang++
        cargo test -p dmbc -p dmbc-capi --color=always --jobs 2 -- --test-threads=1

  save_cache: &save_cache
    save_cache:
      key: dmarket-blockchain-{{ .Branch }}-{{ .Revision }}
      paths:
        - "/project/target/debug/dmbc-node"
        - "/project/target/debug/dmbc-discovery"
        - "/project/target/release/dmbc-node"
        - "/project/target/release/dmbc-discovery"
        - Dockerfile
        - "/project/etc"
        - "/root/.cargo/registry"

  restore_cache: &restore_cache
    restore_cache:
      keys:
        - dmarket-blockchain-{{ .Branch }}-{{ .Revision }}
        - dmarket-blockchain-{{ .Branch }}
        - dmarket-blockchain

  setup_coverage: &setup_coverage
    run:
      name: Install Coverage Dependencies
      command: |
        wget https://github.com/SimonKagstrom/kcov/archive/v34.zip -O /tmp/kcov.zip
        unzip /tmp/kcov.zip
        cd kcov-34
        cmake .
        make -j$(nproc)
        make install

  coverage: &coverage
    run:
      name: Generate Coverage
      command: |
        TESTS=`find target/debug -maxdepth 1 -type f -executable |  grep -v -E '(dmbc-node|dmbc-discovery|dmbc-flooder|dmbc-fuzzer|dmbc-bot|dmbc_capi)'`
        for i in $TESTS; do mkdir -p target/debug/coverage/$i && kcov --verify --include-path dmbc target/debug/coverage/$i $i --test-threads=1; done
        kcov --merge target/debug/coverage/merged/ target/debug/coverage/target/debug/*
        #kcov --verify --include-path dmbc target/debug/coverage $(find target/debug -maxdepth 1 -type f -executable | grep -v -E '(dmbc-node|dmbc-discovery|dmbc-flooder|dmbc-fuzzer|dmbc-bot)')

  build_dev_image: &build_dev_image
    run:
      name: Build and Push docker container
      command: |
        docker build -t globalgames/dmarket-blockchain .
        VERSION=`docker run --rm -ti globalgames/dmarket-blockchain /src/app/dmbc-node -v | awk '{print $3}'`
        TAG=$VERSION-$CIRCLE_BUILD_NUM
        docker tag globalgames/dmarket-blockchain globalgames/dmarket-blockchain:$TAG
        docker tag globalgames/dmarket-blockchain globalgames/dmarket-blockchain:latest
        docker push globalgames/dmarket-blockchain

  build_prod_image: &build_prod_image
    run:
      name: Build and Push docker container
      command: |
        docker build -t globalgames/dmarket-blockchain . --build-arg TYPE=release
        docker tag globalgames/dmarket-blockchain globalgames/dmarket-blockchain:$CIRCLE_TAG
        docker push globalgames/dmarket-blockchain:$CIRCLE_TAG
  
  docker_login: &docker_login
    run:
      name: Docker Login
      command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin        

jobs:
  build_debug:
    working_directory: /project

    docker:
      - image: rust

    steps:
      - checkout
      - *restore_cache
      - *pre_setup
      - *setup_rust
      - *build_dev
      - *build_dev_mobile
      - *run_tests
      - *save_cache
      - *setup_coverage
      - *coverage
      - store_artifacts:
          path: target/debug/coverage/merged

  build_release:
    working_directory: /project

    docker:
      - image: rust

    steps:
      - checkout
      - *restore_cache
      - *pre_setup
      - *setup_rust
      - *build_prod
      - *build_prod_mobile
      - *run_tests
      - *save_cache
      - *setup_coverage
      - *coverage
      - store_artifacts:
          path: target/debug/coverage/merged


  build_docker_dev:
    working_directory: /project
    docker:
      - image: docker:git
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - *restore_cache
      - setup_remote_docker
      - *docker_login
      - *build_dev_image

  build_docker_release:
    working_directory: /project
    docker:
      - image: docker:git
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - *restore_cache
      - setup_remote_docker
      - *docker_login
      - *build_prod_image

workflows:
  version: 2
  debug:
    jobs:
      - build_debug:
          filters:
            tags:
              ignore: /.*/
      - build_docker_dev:
          requires:
            - build_debug
          filters:
            branches:
              only: master
  release:
    jobs:
      - build_release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build_docker_release:
          requires:
            - build_release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
